# Generated by Django 4.1.7 on 2023-02-17 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=1000)),
                ('name_ru', models.CharField(blank=True, max_length=1000)),
                ('name_en', models.CharField(blank=True, max_length=1000)),
                ('description_uz', models.CharField(blank=True, max_length=10000)),
                ('description_ru', models.CharField(blank=True, max_length=10000)),
                ('description_en', models.CharField(blank=True, max_length=10000)),
                ('image', models.ImageField(blank=True, upload_to='media/category')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uz', models.CharField(blank=True, max_length=1000)),
                ('question_ru', models.CharField(blank=True, max_length=1000)),
                ('question_en', models.CharField(blank=True, max_length=1000)),
                ('answer_uz', models.CharField(blank=True, max_length=10000)),
                ('answer_ru', models.CharField(blank=True, max_length=10000)),
                ('answer_en', models.CharField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=1000)),
                ('name_ru', models.CharField(blank=True, max_length=1000)),
                ('name_en', models.CharField(blank=True, max_length=1000)),
                ('description_uz', models.CharField(blank=True, max_length=10000)),
                ('description_ru', models.CharField(blank=True, max_length=10000)),
                ('description_en', models.CharField(blank=True, max_length=10000)),
                ('image', models.ImageField(blank=True, upload_to='media/news')),
                ('date', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=1000)),
                ('name_ru', models.CharField(blank=True, max_length=1000)),
                ('name_en', models.CharField(blank=True, max_length=1000)),
                ('description_uz', models.CharField(blank=True, max_length=10000)),
                ('description_ru', models.CharField(blank=True, max_length=10000)),
                ('description_en', models.CharField(blank=True, max_length=10000)),
                ('image', models.ImageField(blank=True, upload_to='media/our_work')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('top', models.BooleanField(blank=True)),
                ('name_uz', models.CharField(blank=True, max_length=1000)),
                ('name_ru', models.CharField(blank=True, max_length=1000)),
                ('name_en', models.CharField(blank=True, max_length=1000)),
                ('description_uz', models.CharField(blank=True, max_length=10000)),
                ('description_ru', models.CharField(blank=True, max_length=10000)),
                ('description_en', models.CharField(blank=True, max_length=10000)),
                ('image', models.ImageField(blank=True, upload_to='media/product')),
                ('image1', models.ImageField(blank=True, upload_to='media/product')),
                ('image2', models.ImageField(blank=True, upload_to='media/product')),
                ('image3', models.ImageField(blank=True, upload_to='media/product')),
                ('color1', models.CharField(blank=True, max_length=100)),
                ('color2', models.CharField(blank=True, max_length=100)),
                ('color3', models.CharField(blank=True, max_length=100)),
                ('color4', models.CharField(blank=True, max_length=100)),
                ('title_uz', models.CharField(blank=True, max_length=1000)),
                ('title_ru', models.CharField(blank=True, max_length=1000)),
                ('title_en', models.CharField(blank=True, max_length=1000)),
                ('category_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.category')),
            ],
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_uz', models.CharField(blank=True, max_length=1000)),
                ('author_ru', models.CharField(blank=True, max_length=1000)),
                ('author_en', models.CharField(blank=True, max_length=1000)),
                ('description_uz', models.CharField(blank=True, max_length=10000)),
                ('description_ru', models.CharField(blank=True, max_length=10000)),
                ('description_en', models.CharField(blank=True, max_length=10000)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('news_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.news')),
            ],
        ),
    ]
