# Generated by Django 4.1.7 on 2023-02-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='faq',
            table='FAQ',
        ),
        migrations.AlterModelTable(
            name='news',
            table='News',
        ),
        migrations.AlterModelTable(
            name='newscomment',
            table='NewsComment',
        ),
        migrations.AlterModelTable(
            name='ourwork',
            table='OurWork',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
