# Generated by Django 4.1.7 on 2023-02-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_category_table_alter_faq_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='faq',
            table=None,
        ),
        migrations.AlterModelTable(
            name='news',
            table=None,
        ),
        migrations.AlterModelTable(
            name='newscomment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ourwork',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
